Tables:
  ValidityPeriodProjections:
    Columns:
      Id: uniqueidentifier
      WorkItemProjectionId: uniqueidentifier Null
      Status: nvarchar(255)
      StartAt: datetime Null
      EndAt: datetime Null
      ExtendsShift: bit default((0))
      SequenceNumber: int default((0))
    ForeignKeys:
    - WorkItemProjections(WorkItemProjectionId->Id)
    Indexes:
    - Index(WorkItemProjectionId)
    - PrimaryKey:Clustered(Id)
    - Unique(WorkItemProjectionId,SequenceNumber)